### ISSUE TITLE
gym compiling issue

### ISSUE THREAD

**Issue by Mrxiangli** [OpenNetLab/gym#22]
Any idea why compiling gym from source given the following issue?
"
File "/usr/lib/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
"

**Comment by isZXY** [comment]
I Met same problem,
`[0:24:23] Still working on:
[0:24:23]   src/third_party/icu
________ running 'python src/build/landmines.py --landmine-scripts src/build/get_landmines.py --src-dir src' in '/app/AlphaRTC'
________ running 'python src/third_party/depot_tools/update_depot_tools_toggle.py --disable' in '/app/AlphaRTC'
________ running 'python src/build/linux/sysroot_scripts/install-sysroot.py --arch=i386' in '/app/AlphaRTC'
Installing Debian sid i386 root image: /app/AlphaRTC/src/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/36ed2ee83109acdd44af2e522a5e9e0082b074a6/debian_sid_i386_sysroot.tar.xz
Hook 'python src/build/linux/sysroot_scripts/install-sysroot.py --arch=i386' took 16.07 secs
________ running 'python src/build/linux/sysroot_scripts/install-sysroot.py --arch=amd64' in '/app/AlphaRTC'
Installing Debian sid amd64 root image: /app/AlphaRTC/src/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/52cf2961a3cddc0d46e1a2f7d9bf376fc16a61de/debian_sid_amd64_sysroot.tar.xz
Hook 'python src/build/linux/sysroot_scripts/install-sysroot.py --arch=amd64' took 118.55 secs
________ running 'python src/tools/clang/scripts/update.py' in '/app/AlphaRTC'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-n353803-99ac9ce7-1.tgz .......... Done.
Hook 'python src/tools/clang/scripts/update.py' took 83.07 secs
________ running 'python src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/app/AlphaRTC'
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' in '/app/AlphaRTC'
0> Downloading src/buildtools/linux64/clang-format@1baf0089e895c989a311b6a38ed94d0e8be4c0a7...
Downloading 1 files took 25.952111 second(s)
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' took 26.01 secs
________ running 'download_from_google_storage --no_resume --extract --no_auth --bucket chromium-fonts -s src/third_party/test_fonts/test_fonts.tar.gz.sha1' in '/app/AlphaRTC'
0> Downloading src/third_party/test_fonts/test_fonts.tar.gz@a22de844e32a3f720d219e3911c3da3478039f89...
0> Extracting 30 entries from src/third_party/test_fonts/test_fonts.tar.gz to src/third_party/test_fonts/test_fonts
Downloading 1 files took 9.835785 second(s)
________ running 'download_from_google_storage --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz.sha1' in '/app/AlphaRTC'
0> Downloading src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz@92ab0ac3915bc2b50e6a8d7a990522d7355d1ef0...
Downloading 1 files took 106.634947 second(s)
Hook 'download_from_google_storage --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz.sha1' took 106.71 secs
________ running 'download_from_google_storage --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-no-origins-trusty.tgz.sha1' in '/app/AlphaRTC'
0> Downloading src/third_party/instrumented_libraries/binaries/msan-no-origins-trusty.tgz@b02322f976be38aa177febfc8616546b7a23b25e...
Downloading 1 files took 31.220156 second(s)
Hook 'download_from_google_storage --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-no-origins-trusty.tgz.sha1' took 31.29 secs
________ running 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --quiet --bucket chromium-webrtc-resources src/resources' in '/app/AlphaRTC'
mv -fvn src/* .
rm -rf src
gn gen out/Default --args=is_debug=false
Traceback (most recent call last):
  File "/opt/depot_tools/gn.py", line 14, in <module>
    import gclient_paths
  File "/opt/depot_tools/gclient_paths.py", line 24, in <module>
    def FindGclientRoot(from_dir, filename='.gclient'):
  File "/usr/lib/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
make: *** [docker-sync] Error 1
Makefile:47: recipe for target 'docker-sync' failed
Makefile:29: recipe for target 'sync' failed
make[2]: Leaving directory '/data/sigs_users/szxie/ReCoCo/gym_folder/AlphaRTC'
Makefile:61: recipe for target 'sync' failed
make[1]: Leaving directory '/data/sigs_users/szxie/ReCoCo/gym_folder'
/data/sigs_users/szxie/ReCoCo/gym_folder/Makefile:51: recipe for target 'all' failed
make: Leaving directory '/data/sigs_users/szxie/ReCoCo/gym_folder'
make[2]: *** [sync] Error 2
make[1]: *** [sync] Error 2
make: *** [all] Error 2`

**Comment by isZXY** [comment]
Same Problem:

```
[0:24:23] Still working on:
[0:24:23]   src/third_party/icu
________ running 'python src/build/landmines.py --landmine-scripts src/build/get_landmines.py --src-dir src' in '/app/AlphaRTC'
________ running 'python src/third_party/depot_tools/update_depot_tools_toggle.py --disable' in '/app/AlphaRTC'
________ running 'python src/build/linux/sysroot_scripts/install-sysroot.py --arch=i386' in '/app/AlphaRTC'
Installing Debian sid i386 root image: /app/AlphaRTC/src/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/36ed2ee83109acdd44af2e522a5e9e0082b074a6/debian_sid_i386_sysroot.tar.xz
Hook 'python src/build/linux/sysroot_scripts/install-sysroot.py --arch=i386' took 16.07 secs
________ running 'python src/build/linux/sysroot_scripts/install-sysroot.py --arch=amd64' in '/app/AlphaRTC'
Installing Debian sid amd64 root image: /app/AlphaRTC/src/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/52cf2961a3cddc0d46e1a2f7d9bf376fc16a61de/debian_sid_amd64_sysroot.tar.xz
Hook 'python src/build/linux/sysroot_scripts/install-sysroot.py --arch=amd64' took 118.55 secs
________ running 'python src/tools/clang/scripts/update.py' in '/app/AlphaRTC'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-n353803-99ac9ce7-1.tgz .......... Done.
Hook 'python src/tools/clang/scripts/update.py' took 83.07 secs
________ running 'python src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/app/AlphaRTC'
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' in '/app/AlphaRTC'
0> Downloading src/buildtools/linux64/clang-format@1baf0089e895c989a311b6a38ed94d0e8be4c0a7...
Downloading 1 files took 25.952111 second(s)
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s src/buildtools/linux64/clang-format.sha1' took 26.01 secs
________ running 'download_from_google_storage --no_resume --extract --no_auth --bucket chromium-fonts -s src/third_party/test_fonts/test_fonts.tar.gz.sha1' in '/app/AlphaRTC'
0> Downloading src/third_party/test_fonts/test_fonts.tar.gz@a22de844e32a3f720d219e3911c3da3478039f89...
0> Extracting 30 entries from src/third_party/test_fonts/test_fonts.tar.gz to src/third_party/test_fonts/test_fonts
Downloading 1 files took 9.835785 second(s)
________ running 'download_from_google_storage --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz.sha1' in '/app/AlphaRTC'
0> Downloading src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz@92ab0ac3915bc2b50e6a8d7a990522d7355d1ef0...
Downloading 1 files took 106.634947 second(s)
Hook 'download_from_google_storage --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-chained-origins-trusty.tgz.sha1' took 106.71 secs
________ running 'download_from_google_storage --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-no-origins-trusty.tgz.sha1' in '/app/AlphaRTC'
0> Downloading src/third_party/instrumented_libraries/binaries/msan-no-origins-trusty.tgz@b02322f976be38aa177febfc8616546b7a23b25e...
Downloading 1 files took 31.220156 second(s)
Hook 'download_from_google_storage --no_resume --no_auth --bucket chromium-instrumented-libraries -s src/third_party/instrumented_libraries/binaries/msan-no-origins-trusty.tgz.sha1' took 31.29 secs
________ running 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --quiet --bucket chromium-webrtc-resources src/resources' in '/app/AlphaRTC'
mv -fvn src/* .
rm -rf src
gn gen out/Default --args=is_debug=false
Traceback (most recent call last):
  File "/opt/depot_tools/gn.py", line 14, in <module>
    import gclient_paths
  File "/opt/depot_tools/gclient_paths.py", line 24, in <module>
    def FindGclientRoot(from_dir, filename='.gclient'):
  File "/usr/lib/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
make: *** [docker-sync] Error 1
Makefile:47: recipe for target 'docker-sync' failed
Makefile:29: recipe for target 'sync' failed
make[2]: Leaving directory '/data/sigs_users/szxie/ReCoCo/gym_folder/AlphaRTC'
Makefile:61: recipe for target 'sync' failed
make[1]: Leaving directory '/data/sigs_users/szxie/ReCoCo/gym_folder'
/data/sigs_users/szxie/ReCoCo/gym_folder/Makefile:51: recipe for target 'all' failed
make: Leaving directory '/data/sigs_users/szxie/ReCoCo/gym_folder'
make[2]: *** [sync] Error 2
make[1]: *** [sync] Error 2
make: *** [all] Error 2
```

**Comment by zxxia** [comment]
Using python3.8 as suggested [here](https://stackoverflow.com/questions/47218313/use-functools-lru-cache-without-specifying-maxsize-parameter) should fix this error.

The alphartc-compile docker container uses Ubuntu18.04 by default and it has python3.6.
Switching it to Ubuntu20.04 which ships with python3.8 and installing the missing packages solved the compiling issue.

Here is the change in "gym/AlphaRTC/dockers/Dockerfile.compile"
![image](https://github.com/OpenNetLab/gym/assets/13618839/c13c4a28-9bf8-420b-a2b6-f0b317705e08)

**Comment by p2coder** [comment]
Another method is to and '()' on the right of lru_cache
1: use commond: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git on your bare metal, and put the depot_tools directory under the folder  "gym/AlphaRTC/dockers" as a subdirectory of "gym/AlphaRTC/dockers"
2:replace all "@functools.lru_cache" with "@functools.lru_cache()" if there is no () on the right of "@functools.lru_cache"  in the depot_tools folder( I found all the files needed to be changed is ${DEPOT_TOOLS}/gclient_paths.py and ${DEPOT_TOOLS}/git_common.py
3: comment out the line where git clone depot_tools in gym/AlphaRTC/dockers/Dockerfile.compile and use "COPY depot_tools ${DEPOT_TOOLS}" instead
4:  make sync agagin
